name: Build Bash Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/termux/package-builder:latest

    env:
      ANDROID_NDK_HOME: /opt/android-ndk
      ANDROID_SDK_ROOT: /opt/android-sdk
      NDK: /opt/android-ndk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build bash package
        run: |
          ./build-package.sh bash

      - name: Upload deb file
        uses: actions/upload-artifact@v4
        with:
          name: bash-deb
          path: output/*.deb