name: Build Bash Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker container with Termux builder
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/Jj \
            -w /Jj \
            ghcr.io/termux/package-builder:latest \
            ./build-package.sh bash

      - name: Rename .deb files with invalid characters
        run: |
          mkdir -p fixed_output
          for f in output/*.deb; do
            safe_name=$(basename "$f" | tr ':' '_')
            cp "$f" "fixed_output/$safe_name"
          done

      - name: Upload sanitized .deb files
        uses: actions/upload-artifact@v4
        with:
          name: bash-deb
          path: fixed_output/