name: Docker Builder

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Clone the repo
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        cd ./scripts
      
        docker build -t ghcr.io/nikhilroy22/myapp:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/nikhilroy22/myapp:latest