name: Build Cordova Android App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub repo ক্লোন
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js সেটআপ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Cordova ইনস্টল
      - name: Install Cordova
        run: npm install -g cordova

      # 4. Dependencies ইনস্টল
      - name: Install dependencies
        run: npm install

      # 5. Android SDK সেটআপ (Java & Android Tools)
      - name: Setup Java and Android SDK
        uses: android-actions/setup-android@v3

      # 6. Cordova Android Platform যুক্ত করা (যদি আগে না থাকে)
      - name: Add Android platform
        run: |
          if [ ! -d "platforms/android" ]; then
            cordova platform add android
          fi

      # 7. Cordova Android Build
      - name: Build Cordova Android App
        run: cordova build android

      # 8. APK Artifact হিসেবে সংরক্ষণ
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cordova-android-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk